
// import './css/index.css';
// import '../../assets/index1.css';

const html = `
  <!DOCTYPE html>
  <body>
    <h1>css</h1>
    <p>This markup was generated by TencentCloud Edge Functions.</p>
  </body>
`;

const test = '1234';
console.log('test', test);

export function onRequestGet(context) {
  return new Response(html, {
    headers: {
      'content-type': 'text/html; charset=UTF-8',
      'x-edgefunctions-test': 'Welcome to use Edge Functions.',
    },
  });
}
