// const html = `
//   <!DOCTYPE html>
//   <body>
//     <h1>helloworld1111221</h1>
//     <p>This markup was generated by TencentCloud Pages Functions.</p>
//   </body>
// `;


// export function onRequest(context) {
//   return new Response(html, {
//     headers: {
//       'content-type': 'text/html; charset=UTF-8',
//       'x-edgefunctions-test': 'Welcome to use Pages Functions.',
//     },
//   });
// }


const data = {
  content: 5,
};

// console.log(test111);
// console.log('test);
export async function onRequestGet({ request, params, env }) {
  // 读取 Key-Value 数据
  const visitCount = await testkv.get('visitCount');
  
  let visitCountInt = Number(visitCount);
  visitCountInt += 1;

  // 写入 Key-Value 数据
  await testkv.put('visitCount', String(visitCountInt));

  const res = JSON.stringify({
    visitCount: visitCountInt,
  });

  return new Response(res, {
    headers: {
      'content-type': 'application/json; charset=UTF-8',
      'Access-Control-Allow-Origin': '*',
    },
  });
}

// export function onRequestGet(context) {
//   const result = JSON.stringify(data, null, 2);
//   return new Response(result, {
//     headers: {
//       'content-type': 'application/json; charset=UTF-8',
//     },
//   });
// }


