// const html = `
//   <!DOCTYPE html>
//   <body>
//     <h1>helloworld1111221</h1>
//     <p>This markup was generated by TencentCloud Pages Functions.</p>
//   </body>
// `;


// export function onRequest(context) {
//   return new Response(html, {
//     headers: {
//       'content-type': 'text/html; charset=UTF-8',
//       'x-edgefunctions-test': 'Welcome to use Pages Functions.',
//     },
//   });
// }


const data = {
  content: 5,
};

// console.log(test);
// console.log('test);


export function onRequestGet(context) {
  const result = JSON.stringify(data, null, 2);
  return new Response(result, {
    headers: {
      'content-type': 'application/json; charset=UTF-8',
    },
  });
}


