import {a} from './a.js';

const html = `
  <!DOCTYPE html>
  <body>
    <h1>${a}</h1>
    <p>This markup was generated by TencentCloud Edge Functions.</p>
  </body>
`;

const test: string = '1234';
console.log('test', test);

export function onRequestGet(context:any) {
  return new Response(html, {
    headers: {
      'content-type': 'text/html; charset=UTF-8',
      'x-edgefunctions-test': 'Welcome to use Edge Functions.',
    },
  });
}
