const html = `
  <!DOCTYPE html>
  <body>
    <h1>5.tsx</h1>
    <p>This markup was generated by TencentCloud Pages Functions.</p>
  </body>
`;


export async function onRequest(context) {
  console.log(context);
  return new Response(html, {
    headers: {
      'content-type': 'text/html; charset=UTF-8',
      'x-edgefunctions-test': 'Welcome to use Pages Functions.',
    },
  });
}
